services:
  db:
    image: postgres
    container_name: smpcord-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: smpcord
      POSTGRES_PASSWORD: smpcordpass
      POSTGRES_DB: smpcord
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 